name: Deploy

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: joerdav/setup-xc@v1

      - run: xc test
      - run: xc lint

  deploy:
    runs-on: ubuntu-latest
    needs: test
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-2"
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - uses: hashicorp/setup-terraform@v3
      - uses: joerdav/setup-xc@v1

      - run: xc build
      - run: terraform init
        working-directory: ./terraform
      - run: terraform apply -auto-approve
        working-directory: ./terraform
        env:
          TF_VAR_lambda_payload_filename: "../terraform/deployment_package.zip"
